# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77e63a83ad41752032b03e2924f1e642f585eec351607480c6c19fd31baa8cf0c7551c96147f8558e11cfd1a5e30f9a0c5152555d3866adaad88908ab3be2e3d

test:
  secret_key_base: e2bdd5459fa4e209b3fadf52e117b4684fde82ea06ce74a7364fa7db4b187c7f8c8ce1781b40ac3731bb1f06d0ac564b29c95b2b856a78af1c5327f5b168464e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
